### ISSUE TITLE
Utiliser un framework web

### ISSUE THREAD

**Issue by bouttier** [edirTIC31/EDIRTIC31-TwELEC#1]
Pour un petit outil, un micro-framework peut suffir, par exemple http://flask.pocoo.org/.
Sinon il y a Django, qui présente l’avantage de proposer un excellent ORM. D’autre part, s’il l’on venait à vouloir intégrer ce projet à un autre projet Django existant, il suffirait d’importer l’app Django.

**Comment by l-franck** [comment]
Merci pour le tuyau. Je regarde ca des que j'ai un moment !

A un moment ou un autre, il faudra rajouter du traitement au niveau navigateur pour integrer la rétroaction de l'utilisateur sur les résultats de recherche afin de modifier les critères de recherche.

**Comment by l-franck** [comment]
Pour Django, la courbe d'apprentissage est tellement importante que j'hésite. Mais je vois très bien l'importance d'avoir l'application packagée en Django pour plus tard ...

**Comment by nim65s** [comment]
Et c’est à ce moment précis que je remet une couche sur l’importance des formations internes :P

**Comment by l-franck** [comment]
Fait : porté sur Flask.
